row_length: 5
rows_count: 5
row_segments: 
  - straight
hole_prob: 0
hole_size_max: 7
ground_resolution: 0.15
ground_elevation_max: 0.01 #controls the height of the grass -> has to be lower than the dirt 
ground_headland: 1.5 #controls how much area the dirt occupies vs the grass
ground_ditch_depth: 0.05  #controls the height of the dirt  